### ISSUE TITLE
SurveyPro is deleting some submissions

### ISSUE THREAD

**Issue by Brada65** [kordan/moodle-mod_surveypro#430]
Hello Kordan,
we are using SurveyPro plugin on all of our sites, and it is great. But lately we have a problem that SurveyPro is deleting some of our clients submissions. Message from log is stating "user with ID 2 (admin) has deleted the submission with ID 549" and origin is "cli". 
That is very unfortunate for us because we need to keep clients response (even they are partial), and Counselors need to be able to add or change information in restricted part of Survey sometimes after 2 -6 months.
Can you please give us file and line where is that set, and if you can put that as option in future versions of SurveyPro.

**Comment by kordan** [comment]
Ciao Vlad and thanks for using surveypro.
I have never implemented cli in my surveypro. I also have never used it against surveypro and I also ignore if my surveypro responds to cli. I don't think so.
So, if your instance of surveypro responds to cli, as first idea, I believe the code has been modified.
Anyway...
The message you wrote comes from the class "submission_deleted" that is in surveypro/classes/event/submission_deleted.php.
That class trigger the event "submission_deleted" that is created and used in surveypro/classes/utility.php line 373 and 386 from within the method delete_submissions of the class mod_surveypro_utility.
I am really really sad for this incident. Let me say that I strongly use surveypro since its first release and I never loose a record. Never. Not even one.

**Comment by kordan** [comment]
Please let me know the evolution of this story because it is too sad.
I am writing surveypro in the hope people is happy with it so, please, let me understand what is happening.

**Comment by kordan** [comment]
Which branch of surveypro are you using? I hope the master branch. I always update that branch and it is really getting better and working fine.

**Comment by kordan** [comment]
Talking with a wise, really smart and good moodle administrator (and friend) he understood that the responsible of your logs is the cron.
Cron, in fact, is responsible for deletion of "abandoned" submissions.
If a surveypro is created with "Pause/resume" = true and you "pause" your submission instead of submitting it as you should, the submission is saved with status = "in progress".
If you have a surveypro lying on several pages, you fill the surveypro in the first page and then you turn off your computer, the submission of the items of the first page is saved with status = "in progress".

In order to always have a clean database of records, if the user leaves his/her submission "in progress" for a time grater than $maxinputdelay the cron is called to delete it.
If you go to: Home > Site administration > Plugins > Activity modules > Surveypro > Surveypro
you find $maxinputdelay surveypro setting.

The description of "Max input delay" says: "The maximum allowed delay in hours for users to submit a survey. Even if the user is allowed to pause the data entry and restart it later, after the time defined here partial responses will be deleted. Default of 168 hours is equivalent to a week. Set this to 0 (zero) if you really want to allow partial responses (not recommended)."

I hope I was clear to make myself understood.
I forget this detail in the description of surveypro in https://github.com/kordan/moodle-mod_surveypro. I apologise. I will add it as soon as I can.

**Comment by Brada65** [comment]
Yes, that is exactly what is going on. We know that cron was deleted a files, and that cron job is not on the list when you click on Site administration>Server>Scheduled tasks (it would be nice if you can put your cron on that list). This is the reason that I asked you to give us file and lines where we can block cron.

We are using SurveyPro a lot on all our instances of moodle, and some of them are not for learning purposes but for eligibility for some of our programs.

[For Kordan.pdf](https://github.com/kordan/moodle-mod_surveypro/files/1710814/For.Kordan.pdf)

Here in pdf I send you schema of one of our moodle sites (please, this is just for you). 

We don't need clean database of records, because our clients sometimes start SurveyPro form, and then they are not sure what to choose or write (their knowledge of English is low), and that is fine by us, because later in the process they will meet Counselor over Big Blue Button plugin for moodle in that same course and Counselor will help them to finish SurveyPro Form (and add data in counselors part of same form).

The problem here is the time. Sometimes between client starting form and finishing form is more then one month (and cron is deleting files after one week). That is, again, a reason that we want to turn cron off.

It would be nice if you have some outside accessible server on witch I can set our scenarios where we are using SurveyPro to show you how that is working in real life, and also I have some ideas (for SurveyPro) that need some background and explanation.

**Comment by kordan** [comment]
First: thank you for your suggestion. I want to add my cron to the list you mentioned as soon as I can. Moodle grows faster than I the availability of time I have so, sometimes, I miss some detail and this list of cron is, evidently, one of them.

As immediate solution: set "Max input delay" = 0 and cron will not affect any record. To verify that with $maxinputdelay = 0 cron doesn't work, look at: https://github.com/kordan/moodle-mod_surveypro/blob/master/lib.php#L605

Have a nice week end and thanks for all.

**Comment by Brada65** [comment]
Thank you, for this quick response, and should mentioned that we are already set Max input delay = 0, in SurveyPro settings, that is logical solution as you said "Set this to 0 (zero) if you really want to allow partial responses (not recommended).". But still, after that, we have clients records that are deleted. 

Also, did you downloaded pdf, I would like to delete that link now.

**Comment by kordan** [comment]
Yes Vlad. I just copied your pdf. You can take it off. Thanks.
If you like you can even fetch the branch "add_cronjob" in #431 where I added the surveypro cronjob to the list you told me.
BE CAREFULL: the branch has not been tested. It will be tested, probably, next week.

**Comment by kordan** [comment]
Vlad, update your copy of surveypro. I added surveypro cron to Site administration > Server > Scheduled tasks

**Comment by Brada65** [comment]
Thank you Kordan, I will do first thing tomorrow morning (I am not working on Monday).

**Comment by kordan** [comment]
Ahaaaa! I rebuild the ideas driving me to write the cron routine in this way.
The idea was: Database has to be reliable so needs periodic cleanup.

CASE 'save/resume is allowed'
If (save/resume is allowed for this instance of surveypro) {
    Student has a week (by default or ($maxinputdelay * 3600) seconds) to finalise his/her submission.
    If the student leaves the submission in SURVEYPRO_STATUSINPROGRESS status for a time longer than that the submission is dropped.
    Administrator can modulate the time given to students to finalise their response. In particular, by setting ($maxinputdelay = 0), cron intervention is denied.
}

CASE 'save/resume is NOT allowed'
If (save/resume is NOT allowed for this instance of surveypro) {
    Student has 4 hours to finalise his/her submission.
    If the student leaves the submission in SURVEYPRO_STATUSINPROGRESS status for a time longer than 4 hours the submission is dropped.
    Administrator can NOT stop the cron action because database has to be reliable.
}

VERY VERY IMPORTANT:
TAKE IN MIND THAT if you add/remove/alter items to an already answered surveypro, EACH RESPONSES ALREADY SUBMITTED changes its staus to SURVEYPRO_STATUSINPROGRESS.
So, as final consideration:
Even with ($maxinputdelay = 0), cron can still delete abandoned submissions if save/resume is NOT allowed.
I hope this is your case.

**Comment by kordan** [comment]
Vlad, I wrote #434 exactly to meet your needs.
The idea is described in the help button of the surveypro settting 'Keep "in progress" submissions': "Do not delete "in progress" submissions in spite of module policy. "In progress" submissions are supposed to be dropped to always guarantee a good reliability to the final database of responses. If, for any reason, you need to collect also the "in progress" responses, check this box."
Stay tuned.

**Comment by Brada65** [comment]
Hi Kordan, thank you very much on this quick response. I just pickup keepinprogress version, and I will start the testing right away, but it will take some time to get valid results (more then 168 hours).
Anyway I will keep you posted with all facts thru our testing, and eventual errors or messages from testing system.
One of the reasons that we love SurveyPro, is that you are so quick in answers and changes, and open to suggestions (different use of your product).

**Comment by kordan** [comment]
Closed as fixed with some explanations and fix through readme.md and #434
