### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by eldhojoypappara** [kordan/moodle-mod_surveypro#458]
hi team,
I need to make a report for the survey depends on the sections which i created.

**Comment by kordan** [comment]
I am not sure I get what you exctly would like to do.
Can you, please, add some more details?
Thanks in advance.

**Comment by eldhojoypappara** [comment]
Hi,
i need to make some report from the response like what you did with the default template for COLLES template.

For example Colles summery report

**Comment by kordan** [comment]
The original idea was to leave 100% of reports to data analisys software.
Then, colles reports were added "as an exception" because if you use surveypro to deliver a COLLES survey you expect to have "at least" the same output that suvey provide.

So the answer is: no, there are not "built in" reports but reports are plugin of surveypro and you can develop your own report and add (and share) it with the community.
Once you write a new report add it to surveypro/report folder and visit moodle notification page.
You will get your new report added in the page you showed.

**Comment by kordan** [comment]
Closed as it seems an answer was provided.
